### ISSUE TITLE
cc-shim is not showing the commit from where it was built when installed from packages

### ISSUE THREAD

**Issue by gorozco1** [clearcontainers/shim#70]
```
$ /usr/libexec/clear-containers/cc-shim --version
shim version: 3.0.0-alpha.4 (commit: 0)


$ rpm -qa | grep cc-shim
cc-shim-bin-3.0.0beta.2+git.1f545df-2.1.x86_64
cc-shim-3.0.0beta.2+git.1f545df-2.1.x86_64
```

**Comment by erick0z** [comment]
@gorozco1 that's because OBS pulls a github tarball, which normally does not contain the git history, we can append the commit hash when doing make, in this case. The issue I see here is, after doing ./autogen.sh the Makefile has VERSION=3.0.0-alpha4. It's not taking the version from the VERSION file.

**Comment by gorozco1** [comment]
Closing this is a duplicate of #62
